src/Empite.PitchReady.Web/Areas/Client/Models/Athlete.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Empite.PitchReady.Web.Areas.Admin;
namespace Empite.PitchReady.Web.Areas.Admin
{
    public class Athlete
    {
        public string ID { get; set; } = Guid.NewGuid().ToString();
        public string FirstName { get; set; }
        public string email { get; set; }

       
        public Client Client { get; set; }
        public string ClientID { get; set; }
    }
}

src/Empite.PitchReady.Web/Areas/Client/Controllers/AthleteController.cs
using Empite.PitchReady.Entity;
using Empite.PitchReady.Service;
using Empite.PitchReady.Web.Areas.Admin;
using Empite.PitchReady.Web.Areas.Admin.Controllers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Athlete = Empite.PitchReady.Entity.Athlete;

namespace Empite.PitchReady.Web.Areas.Client.Controllers
{
   [Area("Client")]
    public class AthleteController : Controller
    {

        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<ClientController> _logger;
        private readonly IEmailHelper _emailSender;
        private IClientService _clientService;

        public AthleteController(UserManager<ApplicationUser> userManager, ILogger<ClientController> logger, IEmailHelper emailSender, IClientService clientService)
        {
            _userManager = userManager;
            _logger = logger;
            _emailSender = emailSender;
            _clientService = clientService;
        }
        public IActionResult Create()
        {
            return View("Create");
        }

        [HttpPost]
        public async Task<IActionResult> Create(Athlete athlete)
        {

            await _clientService.SaveAthlete(athlete);

            _logger.LogInformation("User created a new Athlete");
            //return Ok(await _clientService.SaveClient(firstName, lastName, new ApplicationUser()));
            return View(athlete);
        }
    }
}

src/Empite.PitchReady.Web/Areas/Client/Views/Athlete/Create.cshtml
@model Empite.PitchReady.Web.Areas.Admin.Client
@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@* Create Athlete View *@
<h1>Create</h1>


@using (Html.BeginForm("Create", "Athlete", FormMethod.Post))
{
    <ul>
        <li>
            <label>First Name</label>
            @Html.TextBoxFor(x => x.FirstName, new { maxlength = 100 })
        </li>
        <li>
            <label>Last Name</label>
            @Html.TextBoxFor(x => x.Email, new { maxlength = 100 })
        </li>
         
    </ul>



    <input type="submit" value="Save" class="btn btn-danger" />
}